name: CITS5553-Group-9
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39hb270ea8_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.10.0=pyhe01879c_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - brotli-python=1.1.0=py39h941272d_3
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h7f933ea_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - frozenlist=1.7.0=py39h2ffb7dc_0
  - greenlet=3.2.4=py39h2769f79_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - jiter=0.10.0=py39hc40b5db_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py39h2804cbe_1
  - langchain=0.3.27=pymin39_hff2d567_0
  - langchain-core=0.3.74=pyhd8ed1ab_0
  - langchain-text-splitters=0.3.9=pyhd8ed1ab_0
  - langsmith=0.3.45=pyhd8ed1ab_0
  - libblas=3.9.0=34_h10e41b3_openblas
  - libcblas=3.9.0=34_hb3479ef_openblas
  - libcxx=20.1.8=hf598326_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libgfortran=15.1.0=hfdf1602_0
  - libgfortran5=15.1.0=hb74de2c_0
  - liblapack=3.9.0=34_hc9a63f6_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.8=hbb9b287_1
  - multidict=6.6.3=py39hafbbd28_0
  - ncurses=6.5=h5e97a16_3
  - numpy=1.26.4=py39h7aa2656_0
  - openai=1.100.2=pyhd8ed1ab_0
  - openssl=3.5.2=he92f556_0
  - orjson=3.11.2=py39hf64921a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h6aaa60c_0
  - pip=25.2=pyh8b19718_0
  - propcache=0.3.1=py39hefdd603_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py39h51e8d5a_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=h7139b31_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39hefdd603_2
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.43=py39he7485ab_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.20.1=py39hefdd603_0
  - zstandard=0.23.0=py39hf3bc14e_2
prefix: /opt/anaconda3/envs/CITS5553-Group-9
